import fs from 'fs/promises';
import path from 'path';
import puppeteer from 'puppeteer';
import prisma from '../lib/prisma';
import crypto from 'crypto';
import QRCode from 'qrcode';
import { v4 as uuidv4 } from 'uuid';

function escapeHtml(value: unknown) {
  return String(value ?? '—')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatDate(value: Date | string | null | undefined) {
  if (!value) return '—';
  const date = typeof value === 'string' ? new Date(value) : value;
  return Number.isNaN(date.getTime()) ? '—' : date.toLocaleDateString('en-GB');
}

const baseStyles = `
  body { font-family: 'Times New Roman', serif; color: #111827; line-height: 1.4; margin: 0; padding: 20px; font-size: 11pt; }
  .page { border: 1.5px solid #111827; padding: 16px 18px 20px; }
  .header { border-bottom: 2px solid #111827; padding-bottom: 8px; margin-bottom: 10px; }
  .title { font-size: 18pt; font-weight: bold; text-align: center; text-transform: uppercase; margin: 2px 0; }
  .subtitle { text-align: center; font-size: 10pt; color: #374151; margin-bottom: 6px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #111827; padding: 6px; vertical-align: top; text-align: left; }
  th { background: #f3f4f6; font-weight: bold; }
  .footer { margin-top: 20px; font-size: 9pt; color: #4b5563; border-top: 1px solid #d1d5db; padding-top: 6px; display: flex; justify-content: space-between; align-items: flex-end; }
  .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 10px; }
  .summary-item { border: 1px solid #111827; padding: 8px; }
`;

function buildAggregateHtml(title: string, subtitle: string, bodyContent: string, digitalSignature?: string, qrCodeDataUri?: string) {
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(title)}</title>
    <style>${baseStyles}</style>
  </head>
  <body>
    <div class="page">
      <div class="header">
        <div class="title">${escapeHtml(title)}</div>
        <div class="subtitle">${escapeHtml(subtitle)}</div>
      </div>
      
      ${bodyContent}
      
      <div class="footer">
        <div>
          Generated by the Forensic Medicine Digital Platform on ${escapeHtml(new Date().toLocaleString('en-GB'))}<br/>
          <small>Signature Hash: ${escapeHtml(digitalSignature || 'N/A')}</small>
        </div>
        ${qrCodeDataUri ? `<div style="text-align: right;"><img src="${qrCodeDataUri}" width="80" height="80" alt="QR Code" /></div>` : ''}
      </div>
    </div>
  </body>
</html>`;
}

async function generatePdf(html: string, reportNamePrefix: string) {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });

  const reportDir = path.resolve(process.cwd(), 'data', 'uploads', 'aggregate_reports');
  await fs.mkdir(reportDir, { recursive: true });
  
  const filename = `${reportNamePrefix}-${uuidv4()}.pdf`;
  const filePath = path.join(reportDir, filename);

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'load' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '12mm', bottom: '12mm', left: '12mm', right: '12mm' }
    });
    
    await fs.writeFile(filePath, pdfBuffer);
    return { pdfBuffer, filePath, filename };
  } finally {
    await browser.close();
  }
}

function generateSignatureAndQrCode(reportType: string) {
  const timestamp = Date.now();
  const rawSignature = `aggregate-${reportType}-${timestamp}-${process.env.JWT_SECRET || 'secret'}`;
  const digitalSignature = crypto.createHash('sha256').update(rawSignature).digest('hex');
  const verificationUrl = `${process.env.PUBLIC_URL || 'http://localhost:4000'}/verify?hash=${digitalSignature}`;
  return { digitalSignature, verificationUrl };
}

// 1. Daily Case Report
export async function generateDailyCaseReportPdf(dateStr?: string) {
  const targetDate = dateStr ? new Date(dateStr) : new Date();
  
  const startOfDay = new Date(targetDate);
  startOfDay.setHours(0, 0, 0, 0);
  
  const endOfDay = new Date(targetDate);
  endOfDay.setHours(23, 59, 59, 999);

  const cases = await prisma.cases.findMany({
    where: {
      opened_date: {
        gte: startOfDay,
        lte: endOfDay
      },
      is_deleted: false
    },
    include: {
      case_type_lu: true,
      users: true,
      case_status_lu: true
    },
    orderBy: { case_id: 'desc' }
  });

  const bodyContent = `
    <p><strong>Date:</strong> ${escapeHtml(formatDate(targetDate))}</p>
    <p><strong>Total Cases:</strong> ${cases.length}</p>
    <table>
      <thead>
        <tr>
          <th>Case Number</th>
          <th>Type</th>
          <th>Status</th>
          <th>Assigned Doctor</th>
        </tr>
      </thead>
      <tbody>
        ${cases.length ? cases.map(c => `
          <tr>
            <td>${escapeHtml(c.case_number)}</td>
            <td>${escapeHtml(c.case_type_lu?.label)}</td>
            <td>${escapeHtml(c.status || c.case_status_lu?.label)}</td>
            <td>${escapeHtml(c.users?.first_name ? `${c.users.first_name} ${c.users.last_name}` : c.users?.username)}</td>
          </tr>
        `).join('') : '<tr><td colspan="4">No cases found for this date.</td></tr>'}
      </tbody>
    </table>
  `;

  const { digitalSignature, verificationUrl } = generateSignatureAndQrCode('daily');
  const qrCodeDataUri = await QRCode.toDataURL(verificationUrl);
  
  const html = buildAggregateHtml('Daily Case Report', 'Summary of cases opened on a specific date', bodyContent, digitalSignature, qrCodeDataUri);
  return await generatePdf(html, 'DAILY-REPORT');
}

// 2. Monthly Report
export async function generateMonthlyReportPdf(month?: number, year?: number) {
  const targetDate = new Date();
  const m = month !== undefined ? month : targetDate.getMonth() + 1;
  const y = year !== undefined ? year : targetDate.getFullYear();
  
  const startOfMonth = new Date(y, m - 1, 1);
  const endOfMonth = new Date(y, m, 0, 23, 59, 59, 999);

  const cases = await prisma.cases.findMany({
    where: {
      opened_date: {
        gte: startOfMonth,
        lte: endOfMonth
      },
      is_deleted: false
    },
    include: {
      case_type_lu: true,
      case_status_lu: true
    }
  });

  const byType: Record<string, number> = {};
  const byStatus: Record<string, number> = {};
  
  cases.forEach(c => {
    const typeLabel = c.case_type_lu?.label || 'Unknown';
    const statusLabel = c.status || c.case_status_lu?.label || 'Unknown';
    byType[typeLabel] = (byType[typeLabel] || 0) + 1;
    byStatus[statusLabel] = (byStatus[statusLabel] || 0) + 1;
  });

  const bodyContent = `
    <p><strong>Month/Year:</strong> ${m}/${y}</p>
    <p><strong>Total Cases:</strong> ${cases.length}</p>
    
    <div class="summary-grid">
      <div class="summary-item">
        <strong>Cases by Type</strong>
        <ul>
          ${Object.entries(byType).map(([t, count]) => `<li>${escapeHtml(t)}: ${count}</li>`).join('')}
        </ul>
      </div>
      <div class="summary-item">
        <strong>Cases by Status</strong>
        <ul>
          ${Object.entries(byStatus).map(([s, count]) => `<li>${escapeHtml(s)}: ${count}</li>`).join('')}
        </ul>
      </div>
    </div>
  `;

  const { digitalSignature, verificationUrl } = generateSignatureAndQrCode('monthly');
  const qrCodeDataUri = await QRCode.toDataURL(verificationUrl);
  
  const html = buildAggregateHtml('Monthly Report', 'Summary of cases opened in a specific month', bodyContent, digitalSignature, qrCodeDataUri);
  return await generatePdf(html, 'MONTHLY-REPORT');
}

// 3. Pending Cases
export async function generatePendingCasesReportPdf() {
  const cases = await prisma.cases.findMany({
    where: {
      OR: [
        { status: { in: ['Pending', 'In Progress', 'Open'] } },
        { case_status_lu: { label: { in: ['Pending', 'In Progress', 'Open'] } } }
      ],
      is_deleted: false
    },
    include: {
      case_type_lu: true,
      users: true,
      case_status_lu: true
    },
    orderBy: { opened_date: 'asc' }
  });

  const bodyContent = `
    <p><strong>Total Pending Cases:</strong> ${cases.length}</p>
    <table>
      <thead>
        <tr>
          <th>Case Number</th>
          <th>Type</th>
          <th>Opened Date</th>
          <th>Assigned Doctor</th>
        </tr>
      </thead>
      <tbody>
        ${cases.length ? cases.map(c => `
          <tr>
            <td>${escapeHtml(c.case_number)}</td>
            <td>${escapeHtml(c.case_type_lu?.label)}</td>
            <td>${escapeHtml(formatDate(c.opened_date))}</td>
            <td>${escapeHtml(c.users?.first_name ? `${c.users.first_name} ${c.users.last_name}` : c.users?.username)}</td>
          </tr>
        `).join('') : '<tr><td colspan="4">No pending cases found.</td></tr>'}
      </tbody>
    </table>
  `;

  const { digitalSignature, verificationUrl } = generateSignatureAndQrCode('pending');
  const qrCodeDataUri = await QRCode.toDataURL(verificationUrl);
  
  const html = buildAggregateHtml('Pending Cases Report', 'List of all currently unresolved cases', bodyContent, digitalSignature, qrCodeDataUri);
  return await generatePdf(html, 'PENDING-REPORT');
}

// 4. Court Report
export async function generateCourtReportPdf() {
  const courtEvents = await prisma.court_event.findMany({
    include: {
      cases: {
        include: {
          case_type_lu: true
        }
      }
    },
    orderBy: { event_date: 'desc' },
    take: 100 // Limit to recent/upcoming 100 for brevity, or can add date params
  });
  
  const upcomingEvents = courtEvents.filter(e => e.event_date && e.event_date >= new Date());
  const pastEvents = courtEvents.filter(e => e.event_date && e.event_date < new Date());

  const buildRows = (events: typeof courtEvents) => events.length ? events.map(e => `
    <tr>
      <td>${escapeHtml(formatDate(e.event_date))}</td>
      <td>${escapeHtml(e.court_name)}</td>
      <td>${escapeHtml(e.cases?.case_number)} (${escapeHtml(e.cases?.case_type_lu?.label)})</td>
      <td>${escapeHtml(e.event_type)}</td>
      <td>${escapeHtml(e.outcome_or_response)}</td>
    </tr>
  `).join('') : '<tr><td colspan="5">No events found.</td></tr>';

  const bodyContent = `
    <h3>Upcoming Court Dates</h3>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Court Name</th>
          <th>Case</th>
          <th>Event Type</th>
          <th>Outcome / Response</th>
        </tr>
      </thead>
      <tbody>${buildRows(upcomingEvents)}</tbody>
    </table>
    
    <h3 style="margin-top: 20px;">Past Court Outcomes</h3>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Court Name</th>
          <th>Case</th>
          <th>Event Type</th>
          <th>Outcome / Response</th>
        </tr>
      </thead>
      <tbody>${buildRows(pastEvents)}</tbody>
    </table>
  `;

  const { digitalSignature, verificationUrl } = generateSignatureAndQrCode('court');
  const qrCodeDataUri = await QRCode.toDataURL(verificationUrl);
  
  const html = buildAggregateHtml('Court Report', 'Upcoming dates and past outcomes', bodyContent, digitalSignature, qrCodeDataUri);
  return await generatePdf(html, 'COURT-REPORT');
}

// 5. Statistical Report
export async function generateStatisticalReportPdf(startDateStr?: string, endDateStr?: string) {
  const whereClause: any = { is_deleted: false };
  let dateText = 'All Time';
  
  if (startDateStr && endDateStr) {
    const sd = new Date(startDateStr);
    const ed = new Date(endDateStr);
    ed.setHours(23, 59, 59, 999);
    whereClause.opened_date = { gte: sd, lte: ed };
    dateText = `${formatDate(sd)} to ${formatDate(ed)}`;
  }

  const cases = await prisma.cases.findMany({
    where: whereClause,
    include: {
      case_type_lu: true,
      case_status_lu: true,
      police_stations: true,
      autopsy_details: true,
      autopsy_case: true
    }
  });

  const total = cases.length;
  const byType: Record<string, number> = {};
  const byPoliceStation: Record<string, number> = {};
  const byMannerOfDeath: Record<string, number> = {};

  cases.forEach(c => {
    byType[c.case_type_lu?.label || 'Unknown'] = (byType[c.case_type_lu?.label || 'Unknown'] || 0) + 1;
    byPoliceStation[c.police_stations?.station_name || 'Unknown'] = (byPoliceStation[c.police_stations?.station_name || 'Unknown'] || 0) + 1;
    
    if (c.autopsy_details?.manner_of_death) {
      byMannerOfDeath[c.autopsy_details.manner_of_death] = (byMannerOfDeath[c.autopsy_details.manner_of_death] || 0) + 1;
    }
  });

  const buildList = (obj: Record<string, number>) => Object.entries(obj)
    .sort((a, b) => b[1] - a[1]) // Sort by count desc
    .map(([k, v]) => `<li>${escapeHtml(k)}: ${v} (${((v/total)*100).toFixed(1)}%)</li>`)
    .join('');

  const bodyContent = `
    <p><strong>Date Range:</strong> ${escapeHtml(dateText)}</p>
    <p><strong>Total Cases Processed:</strong> ${total}</p>
    
    <div class="summary-grid">
      <div class="summary-item">
        <strong>Breakdown by Case Type</strong>
        <ul>${buildList(byType) || '<li>No data</li>'}</ul>
      </div>
      <div class="summary-item">
        <strong>Breakdown by Police Station</strong>
        <ul>${buildList(byPoliceStation) || '<li>No data</li>'}</ul>
      </div>
      <div class="summary-item">
        <strong>Breakdown by Manner of Death (Autopsies)</strong>
        <ul>${buildList(byMannerOfDeath) || '<li>No data</li>'}</ul>
      </div>
    </div>
  `;

  const { digitalSignature, verificationUrl } = generateSignatureAndQrCode('statistical');
  const qrCodeDataUri = await QRCode.toDataURL(verificationUrl);
  
  const html = buildAggregateHtml('Statistical Report', 'Aggregated statistics of case processing', bodyContent, digitalSignature, qrCodeDataUri);
  return await generatePdf(html, 'STATISTICAL-REPORT');
}
